# Generated by Django 3.0.8 on 2020-08-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equ_model',
            name='isbn',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
