# Generated by Django 3.0.8 on 2021-04-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_equ_model_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='equ_model',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
