# Generated by Django 3.0.8 on 2021-05-06 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0003_equ_model_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reantal_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField()),
                ('equ_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Equ_Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
