# Generated by Django 3.0.8 on 2021-05-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_lending_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lending_book',
            old_name='reantal_date',
            new_name='rental_date',
        ),
    ]
